# Generated by Django 5.2.8 on 2026-06-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterKMeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cluster', models.IntegerField(db_column='numeroCluster')),
                ('nombre_cluster', models.CharField(db_column='nombreCluster', max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cluster_k_means',
            },
        ),
        migrations.CreateModel(
            name='EjecucionKMeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_clusters', models.IntegerField(db_column='numeroClusters')),
                ('periodo_inicio', models.DateField(db_column='periodoInicio')),
                ('periodo_fin', models.DateField(db_column='periodoFin')),
                ('variables_usadas', models.JSONField(db_column='variablesUsadas')),
                ('estado', models.CharField(default='EJECUTADO', max_length=20)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, db_column='fechaEjecucion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ejecucion_k_means',
                'ordering': ['-fecha_ejecucion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotacion', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('consumo_total', models.DecimalField(db_column='consumoTotal', decimal_places=4, default=0, max_digits=14)),
                ('costo_total', models.DecimalField(db_column='costoTotal', decimal_places=4, default=0, max_digits=14)),
                ('stock_actual', models.DecimalField(db_column='stockActual', decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'producto_cluster',
            },
        ),
    ]
