# Generated by Django 5.2.8 on 2026-06-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analitica', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionkmeans',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clusterkmeans',
            name='ejecucion',
            field=models.ForeignKey(db_column='idEjecucionKMeans', on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='analitica.ejecucionkmeans'),
        ),
        migrations.AddField(
            model_name='productocluster',
            name='cluster',
            field=models.ForeignKey(db_column='idClusterKMeans', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='analitica.clusterkmeans'),
        ),
        migrations.AddField(
            model_name='productocluster',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
        ),
    ]
