# Generated by Django 6.0.6 on 2026-06-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bajas', '0001_initial'),
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallebaja',
            name='baja',
            field=models.ForeignKey(db_column='idBaja', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bajas.baja'),
        ),
        migrations.AddField(
            model_name='detallebaja',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto'),
        ),
        migrations.AddField(
            model_name='baja',
            name='motivo_baja',
            field=models.ForeignKey(db_column='idMotivoBaja', on_delete=django.db.models.deletion.PROTECT, to='bajas.motivobaja'),
        ),
    ]
