# Generated by Django 6.0.6 on 2026-06-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivobaja',
            options={'ordering': ['nombre']},
        ),
    ]
