# Generated by Django 6.0.6 on 2026-06-22 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0003_alter_motivobaja_options'),
        ('inventario', '0005_capacosto_fecha_vencimiento_capacosto_numero_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebaja',
            name='capa',
            field=models.ForeignKey(blank=True, db_column='idCapaCosto', help_text='Lote especifico a dar de baja; vacio = FIFO automatico', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacosto'),
        ),
    ]
