# Generated by Django 6.0.6 on 2026-06-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ajuste', models.CharField(blank=True, db_column='numeroAjuste', max_length=60)),
                ('fecha_ajuste', models.DateTimeField(auto_now_add=True, db_column='fechaAjuste')),
                ('tipo_ajuste', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], db_column='tipoAjuste', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado')], default='BORRADOR', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ajuste_inventario',
                'ordering': ['-fecha_ajuste', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(db_column='costoUnitario', decimal_places=4, default=0, max_digits=14)),
                ('costo_total', models.DecimalField(db_column='costoTotal', decimal_places=4, default=0, max_digits=14)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'detalle_ajuste',
            },
        ),
    ]
