# Generated by Django 6.0.6 on 2026-06-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.DecimalField(db_column='cantidadInicial', decimal_places=2, max_digits=12)),
                ('cantidad_disponible', models.DecimalField(db_column='cantidadDisponible', decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(db_column='costoUnitario', decimal_places=4, max_digits=14)),
                ('fecha_ingreso', models.DateField(db_column='fechaIngreso')),
                ('origen', models.CharField(choices=[('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste positivo'), ('IMPORTACION', 'Importacion')], max_length=40)),
                ('origen_id', models.IntegerField(blank=True, db_column='origenId', null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('AGOTADA', 'Agotada')], default='ACTIVA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, related_name='capas_costo', to='catalogos.producto')),
            ],
            options={
                'db_table': 'capa_costo',
                'ordering': ['fecha_ingreso', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoCapaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(db_column='cantidadConsumida', decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(db_column='costoUnitario', decimal_places=4, max_digits=14)),
                ('valor_consumido', models.DecimalField(db_column='valorConsumido', decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capa', models.ForeignKey(db_column='idCapaCosto', on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.capacosto')),
            ],
            options={
                'db_table': 'consumo_capa_costo',
            },
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(db_column='cantidadActual', decimal_places=2, default=0, max_digits=12)),
                ('costo_referencial', models.DecimalField(db_column='costoReferencial', decimal_places=4, default=0, max_digits=14)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fechaActualizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='catalogos.producto')),
            ],
            options={
                'db_table': 'inventario_producto',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_column='fechaMovimiento')),
                ('sentido', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20)),
                ('tipo_movimiento', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('BAJA', 'Baja'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('ANULACION', 'Anulacion'), ('IMPORTACION', 'Importacion')], db_column='tipoMovimiento', max_length=40)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario_aplicado', models.DecimalField(db_column='costoUnitarioAplicado', decimal_places=4, default=0, max_digits=14)),
                ('valor_movimiento', models.DecimalField(db_column='valorMovimiento', decimal_places=4, default=0, max_digits=14)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('referencia_tipo', models.CharField(blank=True, db_column='referenciaTipo', max_length=40)),
                ('referencia_id', models.IntegerField(blank=True, db_column='referenciaId', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogos.producto')),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'ordering': ['fecha_movimiento', 'id'],
            },
        ),
    ]
