# Generated by Django 5.2.8 on 2026-06-29 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ajuste', models.DateTimeField(auto_now_add=True, db_column='fechaAjuste')),
                ('tipo_ajuste', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], db_column='tipoAjuste', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado')], default='BORRADOR', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ajuste_inventario',
                'ordering': ['-fecha_ajuste', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_baja', models.CharField(blank=True, db_column='numeroBaja', max_length=60)),
                ('fecha_baja', models.DateTimeField(auto_now_add=True, db_column='fechaBaja')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada')], default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'baja',
                'ordering': ['-fecha_baja', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CapaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.DecimalField(db_column='cantidadInicial', decimal_places=2, max_digits=12)),
                ('cantidad_disponible', models.DecimalField(db_column='cantidadDisponible', decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(db_column='costoUnitario', decimal_places=4, max_digits=14)),
                ('fecha_ingreso', models.DateField(db_column='fechaIngreso')),
                ('origen', models.CharField(choices=[('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste positivo'), ('IMPORTACION', 'Importacion')], max_length=40)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('AGOTADA', 'Agotada')], default='ACTIVA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'capa_costo',
                'ordering': ['fecha_ingreso', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoCapaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(db_column='cantidadConsumida', decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(db_column='costoUnitario', decimal_places=4, max_digits=14)),
                ('valor_consumido', models.DecimalField(db_column='valorConsumido', decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consumo_capa_costo',
            },
        ),
        migrations.CreateModel(
            name='DetalleAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(db_column='costoUnitario', decimal_places=4, default=0, max_digits=14)),
                ('costo_total', models.DecimalField(db_column='costoTotal', decimal_places=4, default=0, max_digits=14)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'detalle_ajuste',
            },
        ),
        migrations.CreateModel(
            name='DetalleBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total_baja', models.DecimalField(db_column='costoTotalBaja', decimal_places=4, default=0, max_digits=14)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'detalle_baja',
            },
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(db_column='cantidadActual', decimal_places=2, default=0, max_digits=12)),
                ('costo_referencial', models.DecimalField(db_column='costoReferencial', decimal_places=4, default=0, max_digits=14)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fechaActualizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventario_producto',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='MotivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'motivo_baja',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(db_column='fechaMovimiento', default=django.utils.timezone.now)),
                ('sentido', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20)),
                ('tipo_movimiento', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('BAJA', 'Baja'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('ANULACION', 'Anulacion'), ('IMPORTACION', 'Importacion')], db_column='tipoMovimiento', max_length=40)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario_aplicado', models.DecimalField(db_column='costoUnitarioAplicado', decimal_places=4, default=0, max_digits=14)),
                ('valor_movimiento', models.DecimalField(db_column='valorMovimiento', decimal_places=4, default=0, max_digits=14)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('referencia_tipo', models.CharField(blank=True, db_column='referenciaTipo', max_length=40)),
                ('referencia_id', models.IntegerField(blank=True, db_column='referenciaId', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'ordering': ['fecha_movimiento', 'id'],
            },
        ),
    ]
