# Generated by Django 5.2.8 on 2026-06-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baja',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacosto',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, related_name='capas_costo', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='consumocapacosto',
            name='capa',
            field=models.ForeignKey(db_column='idCapaCosto', on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.capacosto'),
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='ajuste',
            field=models.ForeignKey(db_column='idAjusteInventario', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ajusteinventario'),
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='detallebaja',
            name='baja',
            field=models.ForeignKey(db_column='idBaja', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.baja'),
        ),
        migrations.AddField(
            model_name='detallebaja',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='producto',
            field=models.OneToOneField(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='baja',
            name='motivo_baja',
            field=models.ForeignKey(db_column='idMotivoBaja', on_delete=django.db.models.deletion.PROTECT, to='inventario.motivobaja'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumocapacosto',
            name='movimiento',
            field=models.ForeignKey(db_column='idMovimientoInventario', on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='inventario.movimientoinventario'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha_movimiento'], name='movimiento__fechaMo_25ca4f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'fecha_movimiento'], name='movimiento__idProdu_37ca15_idx'),
        ),
    ]
