# Generated by Django 6.0.6 on 2026-06-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumocapacosto',
            name='movimiento',
            field=models.ForeignKey(db_column='idMovimientoInventario', on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='inventario.movimientoinventario'),
        ),
    ]
