# Generated by Django 6.0.6 on 2026-06-22 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_movimiento',
            field=models.DateTimeField(db_column='fechaMovimiento', default=django.utils.timezone.now),
        ),
    ]
