# Generated by Django 6.0.6 on 2026-06-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientoinventario_fecha_movimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioproducto',
            options={'ordering': ['producto__nombre']},
        ),
    ]
