# Generated by Django 6.0.6 on 2026-06-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventarioproducto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacosto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_column='fechaVencimiento', null=True),
        ),
        migrations.AddField(
            model_name='capacosto',
            name='numero_lote',
            field=models.CharField(blank=True, db_column='numeroLote', default='', max_length=60),
        ),
    ]
