# Generated by Django 6.0.6 on 2026-06-23 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('inventario', '0005_capacosto_fecha_vencimiento_capacosto_numero_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha_movimiento'], name='movimiento__fechaMo_25ca4f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'fecha_movimiento'], name='movimiento__idProdu_37ca15_idx'),
        ),
    ]
