# Generated by Django 5.2.8 on 2026-06-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(blank=True, db_column='numeroOrden', max_length=60)),
                ('numero_factura', models.CharField(blank=True, db_column='numeroFactura', max_length=60)),
                ('fecha_compra', models.DateField(db_column='fechaCompra')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('total_compra', models.DecimalField(db_column='totalCompra', decimal_places=4, default=0, max_digits=14)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compra',
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(db_column='costoUnitario', decimal_places=4, max_digits=14)),
                ('costo_total', models.DecimalField(db_column='costoTotal', decimal_places=4, default=0, max_digits=14)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='fechaVencimiento', null=True)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'detalle_compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('nit', models.CharField(blank=True, max_length=40)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proveedor',
                'ordering': ['nombre'],
            },
        ),
    ]
