# Generated by Django 5.2.8 on 2026-06-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(db_column='idCompra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, db_column='idUnidadMedida', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.unidadmedida'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.proveedor'),
        ),
    ]
