# Generated by Django 6.0.6 on 2026-06-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='numero_lote',
            field=models.CharField(blank=True, db_column='numeroLote', default='', max_length=60),
        ),
    ]
