# Generated by Django 6.0.6 on 2026-06-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.IntegerField(db_column='numeroFila')),
                ('datos_originales', models.JSONField(db_column='datosOriginales')),
                ('estado_fila', models.CharField(db_column='estadoFila', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, db_column='mensajeError')),
                ('referencia_creada_tipo', models.CharField(blank=True, db_column='referenciaCreadaTipo', max_length=40)),
                ('referencia_creada_id', models.IntegerField(blank=True, db_column='referenciaCreadaId', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'detalle_importacion',
            },
        ),
        migrations.CreateModel(
            name='ImportacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_importacion', models.CharField(choices=[('INVENTARIO_INICIAL', 'Inventario inicial'), ('COMPRAS', 'Compras'), ('VENTAS', 'Ventas'), ('BAJAS', 'Bajas')], db_column='tipoImportacion', max_length=40)),
                ('nombre_archivo', models.CharField(db_column='nombreArchivo', max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('CONFIRMADO', 'Confirmado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('total_registros', models.IntegerField(db_column='totalRegistros', default=0)),
                ('registros_validos', models.IntegerField(db_column='registrosValidos', default=0)),
                ('registros_observados', models.IntegerField(db_column='registrosObservados', default=0)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, db_column='fechaImportacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'importacion_archivo',
                'ordering': ['-fecha_importacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LogImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('campo', models.CharField(blank=True, max_length=80)),
                ('valor', models.CharField(blank=True, max_length=255)),
                ('tipo_error', models.CharField(db_column='tipoError', max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('procesado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'log_importacion',
            },
        ),
    ]
