# Generated by Django 6.0.6 on 2026-06-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionarchivo',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleimportacion',
            name='importacion',
            field=models.ForeignKey(db_column='idImportacionArchivo', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='importaciones.importacionarchivo'),
        ),
        migrations.AddField(
            model_name='logimportacion',
            name='importacion',
            field=models.ForeignKey(db_column='idImportacionArchivo', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='importaciones.importacionarchivo'),
        ),
    ]
