# Generated by Django 5.2.8 on 2026-06-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoExportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(db_column='tipoDocumento', max_length=60)),
                ('nombre_archivo', models.CharField(db_column='nombreArchivo', max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, db_column='rutaArchivo', max_length=255)),
                ('referencia_tipo', models.CharField(blank=True, db_column='referenciaTipo', max_length=40)),
                ('referencia_id', models.IntegerField(blank=True, db_column='referenciaId', null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='fechaGeneracion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documento_exportado',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_reporte', models.CharField(db_column='tipoReporte', max_length=60)),
                ('formato', models.CharField(max_length=20)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('ruta_archivo', models.CharField(blank=True, db_column='rutaArchivo', max_length=255)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='fechaGeneracion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
    ]
