# Generated by Django 6.0.6 on 2026-06-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categoria_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('abreviatura', models.CharField(max_length=20)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unidad_medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(db_column='codigoProducto', max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_producto', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('MATERIAL', 'Material'), ('INSUMO', 'Insumo'), ('ESPECIAL', 'Producto especial')], db_column='tipoProducto', default='MEDICAMENTO', max_length=40)),
                ('precio_venta', models.DecimalField(db_column='precioVenta', decimal_places=4, default=0, max_digits=14)),
                ('costo_referencial', models.DecimalField(db_column='costoReferencial', decimal_places=4, default=0, max_digits=14)),
                ('stock_minimo', models.DecimalField(db_column='stockMinimo', decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fechaCreacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(db_column='idCategoriaProducto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogos.categoriaproducto')),
                ('unidad_medida', models.ForeignKey(db_column='idUnidadMedida', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogos.unidadmedida')),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
    ]
