# Generated by Django 6.0.6 on 2026-06-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(blank=True, db_column='numeroBoleta', max_length=60)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_column='fechaVenta')),
                ('tipo_venta', models.CharField(choices=[('VENTA', 'Venta'), ('DISPENSACION', 'Dispensacion')], db_column='tipoVenta', default='VENTA', max_length=40)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('total_venta', models.DecimalField(db_column='totalVenta', decimal_places=4, default=0, max_digits=14)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venta',
                'ordering': ['-fecha_venta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(db_column='precioUnitario', decimal_places=4, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_total_salida', models.DecimalField(db_column='costoTotalSalida', decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
                ('venta', models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='AnulacionBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anulacion', models.DateTimeField(auto_now_add=True, db_column='fechaAnulacion')),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('restaura_stock', models.BooleanField(db_column='restauraStock', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, related_name='anulaciones', to='ventas.venta')),
            ],
            options={
                'db_table': 'anulacion_boleta',
            },
        ),
    ]
