# Generated by Django 5.2.8 on 2026-06-29 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_entrega',
            field=models.CharField(choices=[('PENDIENTE_ENTREGA', 'Pendiente de entrega'), ('ENTREGADA', 'Entregada'), ('NO_ENTREGADA', 'No entregada')], db_column='estadoEntrega', default='PENDIENTE_ENTREGA', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADA', 'Pagada'), ('RECHAZADA', 'Rechazada')], db_column='estadoPago', default='PENDIENTE_PAGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=20),
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(blank=True, db_column='numeroComprobante', max_length=60)),
                ('monto_pagado', models.DecimalField(db_column='montoPagado', decimal_places=4, default=0, max_digits=14)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, db_column='fechaPago')),
                ('estado_verificacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], db_column='estadoVerificacion', default='PENDIENTE', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='ventas.venta')),
            ],
            options={
                'db_table': 'comprobante_pago',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
