# Generated by Django 5.2.8 on 2026-06-29 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_inicio', models.DateField(db_column='fechaInicio')),
                ('fecha_fin', models.DateField(db_column='fechaFin')),
                ('estado', models.CharField(default='ABIERTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='SaldoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial_cantidad', models.DecimalField(db_column='saldoInicialCantidad', decimal_places=2, default=0, max_digits=12)),
                ('saldo_inicial_valor', models.DecimalField(db_column='saldoInicialValor', decimal_places=4, default=0, max_digits=14)),
                ('saldo_final_cantidad', models.DecimalField(db_column='saldoFinalCantidad', decimal_places=2, default=0, max_digits=12)),
                ('saldo_final_valor', models.DecimalField(db_column='saldoFinalValor', decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saldo_periodo',
            },
        ),
        migrations.CreateModel(
            name='DetalleKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=120)),
                ('tipo_movimiento', models.CharField(db_column='tipoMovimiento', max_length=40)),
                ('costo_unitario_referencial', models.DecimalField(db_column='costoUnitarioReferencial', decimal_places=4, default=0, max_digits=14)),
                ('entrada_cantidad', models.DecimalField(db_column='entradaCantidad', decimal_places=2, default=0, max_digits=12)),
                ('entrada_valor', models.DecimalField(db_column='entradaValor', decimal_places=4, default=0, max_digits=14)),
                ('salida_cantidad', models.DecimalField(db_column='salidaCantidad', decimal_places=2, default=0, max_digits=12)),
                ('salida_valor', models.DecimalField(db_column='salidaValor', decimal_places=4, default=0, max_digits=14)),
                ('saldo_cantidad', models.DecimalField(db_column='saldoCantidad', decimal_places=2, default=0, max_digits=12)),
                ('saldo_valor', models.DecimalField(db_column='saldoValor', decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movimiento', models.ForeignKey(blank=True, db_column='idMovimientoInventario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimientoinventario')),
            ],
            options={
                'db_table': 'detalle_kardex',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KardexGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_column='fechaInicio')),
                ('fecha_fin', models.DateField(db_column='fechaFin')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='fechaGeneracion')),
                ('saldo_inicial_cantidad', models.DecimalField(db_column='saldoInicialCantidad', decimal_places=2, default=0, max_digits=12)),
                ('saldo_inicial_valor', models.DecimalField(db_column='saldoInicialValor', decimal_places=4, default=0, max_digits=14)),
                ('saldo_final_cantidad', models.DecimalField(db_column='saldoFinalCantidad', decimal_places=2, default=0, max_digits=12)),
                ('saldo_final_valor', models.DecimalField(db_column='saldoFinalValor', decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'db_table': 'kardex_generado',
            },
        ),
    ]
