# Generated by Django 5.2.8 on 2026-06-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('kardex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexgenerado',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallekardex',
            name='kardex',
            field=models.ForeignKey(db_column='idKardexGenerado', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='kardex.kardexgenerado'),
        ),
        migrations.AddField(
            model_name='kardexgenerado',
            name='periodo',
            field=models.ForeignKey(blank=True, db_column='idPeriodo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kardex.periodo'),
        ),
        migrations.AddField(
            model_name='saldoperiodo',
            name='periodo',
            field=models.ForeignKey(db_column='idPeriodo', on_delete=django.db.models.deletion.CASCADE, to='kardex.periodo'),
        ),
        migrations.AddField(
            model_name='saldoperiodo',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='saldoperiodo',
            unique_together={('periodo', 'producto')},
        ),
    ]
