# Generated by Django 5.2.8 on 2026-06-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=60)),
                ('accion', models.CharField(max_length=60)),
                ('entidad', models.CharField(max_length=60)),
                ('id_entidad', models.IntegerField(blank=True, db_column='idEntidad', null=True)),
                ('valores_anteriores', models.JSONField(blank=True, db_column='valoresAnteriores', null=True)),
                ('valores_nuevos', models.JSONField(blank=True, db_column='valoresNuevos', null=True)),
                ('ip_origen', models.CharField(blank=True, db_column='ipOrigen', max_length=60)),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True, db_column='fechaOperacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bitacora_operacion',
                'ordering': ['-fecha_operacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parametro_sistema',
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('modulo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('requiere_motivo', models.BooleanField(db_column='requiereMotivo', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_operacion',
            },
        ),
    ]
