# Generated by Django 5.2.8 on 2026-06-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraoperacion',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bitacoraoperacion',
            name='tipo_operacion',
            field=models.ForeignKey(blank=True, db_column='idTipoOperacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditoria.tipooperacion'),
        ),
    ]
